### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by transitive-bullshit** [hydrateio/docz-plugin-storybook#12]
This module is stable and works well with manual Story rendering from within Docz.

In order to get to a v1.0 candidate, we should resolve the following issues:

- [ ] #2 Story component isolation (styles, js) - WIP #6
- [ ] #7 Support automated docz contents with stories (Automatic population of docz's contents with stories is currently a WIP) - WIP #4
- [ ] #8 Add support for storybook webpack configs (Some storybook addons and webpack customizations will take extra steps to get working from within Docz)

Issues that I believe fall beyond v1.0 include:

- [ ] #3 Full support for docz story hot reloading 
- [ ] #9 Add support for the most popular storybook addons
- [ ] #10 Integration tests with various storybook fixtures
- [ ] #11 Add FAQ to answer anticipated / common questions
